version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/hori-ryota/zaperr
    steps:
      - checkout

      - run: go get github.com/mattn/goveralls

      - run: go get -v -t -d ./...
      - run: go test -v -cover -race -coverprofile=./coverage.out ./...

      - run: goveralls -coverprofile=./coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
